name: KnokkoCore
main: nl.knokko.core.plugin.CorePlugin
api-version: 1.14
version: 1.14 13
commands:
  knokkocore:
    description: Test and debug command for the Knokko Core Plugin
    useage: /knokkocore itemattribute/itemname/test
    aliases: [knokko]
