name: KnokkoCore
main: nl.knokko.core.plugin.CorePlugin
api-version: 1.13
version: 1.13 10
commands:
  knokkocore:
    description: Test and debug command for the Knokko Core Plugin
    useage: /knokkocore itemattribute/itemname/test
    aliases: [knokko]
